name: Merge-to-develop

on:
  push:
    branches:
      - 'feature/**'

jobs:
  update:
    name: update-branch
    if: ${{ contains(github.event.head_commit.message, '[dev]') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: merge-init
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: 'develop'
          target-branch: ${{ github.ref_name }}
          commit-message: ${{github.event.head_commit.message}}

  test:
    name: Test
    needs: update
    uses: ./.github/workflows/test.yml

  merge:
    name: Automerge
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: merge-to-develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref_name }}
          target-branch: 'develop'
          commit-message: ${{github.event.head_commit.message}}
  

