name: CI

on:
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: Configuracion de paython
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'
      - name: Intalación de dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Correr pruebas
        id: run-test
        run: python -m unittest discover -s tests -v
      - name: Cobertura
        run: |
          python -m coverage run -m unittest discover -s tests -v
          python -m coverage html
  merge:
    name: Automerge
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: merge-to-develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref_name }}
          target-branch: 'develop'

