name: Deploy-main

on:
  merge:
    branches:
      - 'develop'

jobs:
  create-branch:
    name: Merge-develop
    if: ${{ contains(github.event.head_commit.message, '[deploy]') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2

      - name: Git Semantic Version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          major_pattern: "(MAJOR)"
          minor_pattern: '(MINOR)'
          version_format: '${major}.${minor}'

      - name: Crear rama
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          git checkout -b release/$VERSION
          git push -f -u origin release/$VERSION

      - name: merge-to-develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: 'develop'
          target-branch: 'release/${{ steps.version.outputs.version }}'

      - name: Configuracion de paython
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'

      - name: Intalación de dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Correr pruebas
        id: run-test
        run: python -m unittest discover -s tests -v

      - name: Cobertura
        run: |
          python -m coverage run -m unittest discover -s tests -v
          python -m coverage html

      - name: deploy
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: 'release/${{ steps.version.outputs.version }}'
          target-branch: 'main'


