name: Deploy

on:
  create:
    branches:
      - 'release/**'

jobs:
  mergetodevelop:
    name: Merge-develop
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: merge-to-develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: 'develop'
          target-branch: ${{ github.ref_name }}

  testrelease:
    name: Test
    uses: ./.github/workflows/test.yml

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: merge-to-main
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref_name }}
          target-branch: 'main'

