name: Test

on:
  workflow_call:


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: Configuracion de paython
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'
      - name: Intalación de dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Correr pruebas
        id: run-test
        run: python -m unittest discover -s tests -v
      - name: Cobertura
        run: |
          python -m coverage run -m unittest discover -s tests -v
          python -m coverage html
